TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Tags: 
        - Key: BusinessUnit
          Value: !Ref BusinessUnitTag
        - Key: Customer
          Value: !Ref CustomerTag
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: ProductOwner
          Value: !Ref ProductOwnerTag
        - Key: Provisioned
          Value: !Ref ProvisionedTag
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /healthcheck
      HealthCheckProtocol: HTTP
      HealthCheckPort: !Ref ContainerPort
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      Matcher: 
        HttpCode: '200'
      Name: !Ref ContainerName
      Port: !Ref ContainerPort
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref 'VpcId'
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: TargetGroup
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'TargetGroup'
      Conditions:
      - Field: path-pattern
        Values: ['/*']
      ListenerArn: !Ref AlbListenerArn
      Priority: !Ref RulePriority
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: #servicename-logs
      RetentionInDays: !Ref LogRetention
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: #Service Name-SG
      VpcId: !Ref VpcId
      SecurityGroupIngress: